application: jobsforhackers
version: 1
runtime: python
api_version: 1

handlers:
- url: /console/static
  static_dir: console/app/view/static

- url: /console.*
  script: console/app/console.py

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /check_queued_jobs
  script: services.py
  login: admin

- url: /rss
  script: services.py

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /jobs/(new|my)
  script: bootstrap.py
  login: required

- url: /jobs/(check|edit|delete)/(\d+)
  script: bootstrap.py
  login: required

- url: /(.*)
  script: bootstrap.py
