application: jobsforhackers
version: 1
runtime: python
api_version: 1

handlers:

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /jobs/(new|my)
  script: bootstrap.py
  login: required

- url: /jobs/(check|edit|delete)/(\d+)
  script: bootstrap.py
  login: required

- url: /(.*)
  script: bootstrap.py
