application: jobsforhackers
version: 1
runtime: python
api_version: 1

handlers:

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /jobs/new
  script: bootstrap.py
  login: required

- url: /jobs/my
  script: bootstrap.py
  login: required

- url: /jobs/check/(\d+)
  script: bootstrap.py
  login: required

- url: /jobs/edit/(\d+)
  script: bootstrap.py
  login: required

- url: /jobs/delete/(\d+)
  script: bootstrap.py
  login: required

- url: /(.*)
  script: bootstrap.py
