application: jobsforhackers
version: 1
runtime: python
api_version: 1

handlers:
- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /jobs/check_queued
  script: bootstrap.py
  login: admin

- url: /jobs/(new|my)
  script: bootstrap.py
  login: required

- url: /jobs/(check|edit|delete)/(\d+)
  script: bootstrap.py
  login: required

- url: /(.*)
  script: bootstrap.py
